[build]
  command = "npm install && npm run build"
  publish = "dist"

# >>> Add this block <<<
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]

# Map /api/* → Netlify Functions
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200
  force  = true

# SPA fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
